apiVersion: v1
kind: PErsistentVolume

metadata:
  name: mongo-pv
  namespace: three-tier

spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
hostPath:
  path: /data/db
